"""add_user_id_to_surveys

Revision ID: a1ab7b3749fe
Revises: 001_initial
Create Date: 2025-12-25 12:36:27.301393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
from sqlalchemy.exc import OperationalError

# revision identifiers, used by Alembic.
revision: str = 'a1ab7b3749fe'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Participations table (drop) - may not exist on fresh DB
    try:
        op.drop_index(op.f('ix_participations_fingerprint_hash'), table_name='participations')
    except OperationalError:
        pass
    try:
        op.drop_index(op.f('ix_participations_survey_id'), table_name='participations')
    except OperationalError:
        pass
    try:
        op.drop_table('participations')
    except OperationalError:
        pass  # Table doesn't exist, that's fine

    # Survey Events table adjustments
    try:
        with op.batch_alter_table('survey_events', schema=None) as batch_op:
            batch_op.add_column(sa.Column('question_index', sa.Integer(), nullable=True))
            batch_op.alter_column('session_id',
                   existing_type=sa.VARCHAR(length=36),
                   nullable=False)
            try:
                batch_op.drop_index('ix_survey_events_created_at')
            except (OperationalError, ValueError):
                pass
            batch_op.create_index(batch_op.f('ix_survey_events_session_id'), ['session_id'], unique=False)
            try:
                batch_op.drop_column('meta')
            except (OperationalError, KeyError):
                pass
    except OperationalError:
        pass  # Table might not exist or already modified

    # Surveys table adjustments
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))  # Nullable for existing data
        
        batch_op.alter_column('is_active',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Boolean(),
               existing_nullable=True)
        
        batch_op.create_index(batch_op.f('ix_surveys_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_surveys_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_surveys_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_constraint('fk_surveys_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_surveys_user_id'))
        batch_op.drop_index(batch_op.f('ix_surveys_slug'))
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('slug')

    with op.batch_alter_table('survey_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta', sqlite.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_survey_events_session_id'))
        batch_op.alter_column('session_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('question_index')

    op.create_table('participations',
        sa.Column('id', sa.VARCHAR(length=36), nullable=False),
        sa.Column('survey_id', sa.VARCHAR(length=100), nullable=False),
        sa.Column('fingerprint_hash', sa.VARCHAR(length=64), nullable=False),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participations_survey_id'), 'participations', ['survey_id'], unique=False)
    op.create_index(op.f('ix_participations_fingerprint_hash'), 'participations', ['fingerprint_hash'], unique=False)
    # ### end Alembic commands ###
