"""add_auth_state_table_for_secure_oauth

Revision ID: b2cd8e485012
Revises: a1ab7b3749fe
Create Date: 2025-12-30 15:54:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cd8e485012'
down_revision = 'a1ab7b3749fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_states',
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_states')
    # ### end Alembic commands ###
